// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saloon_Assesement_1.Data;

namespace Saloon_Assesement_1.Migrations
{
    [DbContext(typeof(Saloon_Assesement_1Context))]
    partial class Saloon_Assesement_1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Saloon_Assesement_1.Models.Beautician", b =>
                {
                    b.Property<int>("Beautician_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beautician_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Contact_Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Joining_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParlourID")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Beautician_ID");

                    b.HasIndex("ParlourID");

                    b.ToTable("Beautician");
                });

            modelBuilder.Entity("Saloon_Assesement_1.Models.Customer", b =>
                {
                    b.Property<int>("Customer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Contact_Number")
                        .HasColumnType("int");

                    b.Property<string>("Customer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Expenses")
                        .HasColumnType("int");

                    b.Property<int>("ParlourID")
                        .HasColumnType("int");

                    b.HasKey("Customer_ID");

                    b.HasIndex("ParlourID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Saloon_Assesement_1.Models.Parlour", b =>
                {
                    b.Property<int>("Parlour_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Contact_Number")
                        .HasColumnType("int");

                    b.Property<string>("Parlour_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parlour_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Parlour_ID");

                    b.ToTable("Parlour");
                });

            modelBuilder.Entity("Saloon_Assesement_1.Models.Product", b =>
                {
                    b.Property<int>("Product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Expiry_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParlourID")
                        .HasColumnType("int");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Product_ID");

                    b.HasIndex("ParlourID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Saloon_Assesement_1.Models.Beautician", b =>
                {
                    b.HasOne("Saloon_Assesement_1.Models.Parlour", "Parlour_obj")
                        .WithMany()
                        .HasForeignKey("ParlourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Saloon_Assesement_1.Models.Customer", b =>
                {
                    b.HasOne("Saloon_Assesement_1.Models.Parlour", "Parlour_obj")
                        .WithMany()
                        .HasForeignKey("ParlourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Saloon_Assesement_1.Models.Product", b =>
                {
                    b.HasOne("Saloon_Assesement_1.Models.Parlour", "Parlour_obj")
                        .WithMany()
                        .HasForeignKey("ParlourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
